### ISSUE TITLE
cmd/diffgrep: Broken link in package comment.

### ISSUE THREAD

**Issue by dmitshur** [rogpeppe/misc#4]
The documentation for https://godoc.org/github.com/rogpeppe/misc/cmd/diffgrep says:

> Credit to https://godoc.org/github.com/sourcegraph/go-diff for making it possible to implement this in less than an hour.

That's a broken link. If you want to point to the package godoc, you should use the correct vanity import path:

https://godoc.org/sourcegraph.com/sourcegraph/go-diff/diff

Alternatively, if you want to link to the GitHub repository, then it should be:

https://github.com/sourcegraph/go-diff

**Comment by rogpeppe** [comment]
Thanks. Fixed.
